In [3]:
import tensorflow as tf
from publicMethod import *

In [4]:
file_name = "data/GSOD_2021/010010-99999-2021.op"
avg_data, min_data, max_data = open_file(file_name)
(train_data, train_label), (test_data, test_label) = generate(int(0.75*len(avg_data)), avg_data)

In [15]:
train_data.shape, train_label.shape, "", train_data[0:10], train_label[:10]

((150, 7),
 (150,),
 '',
 array([[23.4, 31.5, 35. , 35.4, 27.5, 23.6, 18.7],
        [31.5, 35. , 35.4, 27.5, 23.6, 18.7, 26.9],
        [35. , 35.4, 27.5, 23.6, 18.7, 26.9, 31.7],
        [35.4, 27.5, 23.6, 18.7, 26.9, 31.7, 32.1],
        [27.5, 23.6, 18.7, 26.9, 31.7, 32.1, 31.9],
        [23.6, 18.7, 26.9, 31.7, 32.1, 31.9, 29.2],
        [18.7, 26.9, 31.7, 32.1, 31.9, 29.2, 29.5],
        [26.9, 31.7, 32.1, 31.9, 29.2, 29.5, 33.5],
        [31.7, 32.1, 31.9, 29.2, 29.5, 33.5, 32.5],
        [32.1, 31.9, 29.2, 29.5, 33.5, 32.5, 32.2]]),
 array([31.7, 32.1, 31.9, 29.2, 29.5, 33.5, 32.5, 32.2, 33.9, 29.2]))

In [24]:
# 改变数据的形状以适合训练
train_label = train_label.reshape(-1,1)
test_label = test_label.reshape(-1, 1)

In [25]:
train_label.shape, train_label

((150, 1),
 array([[31.7],
        [32.1],
        [31.9],
        [29.2],
        [29.5],
        [33.5],
        [32.5],
        [32.2],
        [33.9],
        [29.2],
        [27.3],
        [30.2],
        [28.7],
        [29.8],
        [26.5],
        [21.8],
        [25.9],
        [30.2],
        [30.1],
        [27.2],
        [25.8],
        [28.2],
        [28.5],
        [27.5],
        [23. ],
        [26.9],
        [30.1],
        [31.4],
        [30.9],
        [26.3],
        [24.5],
        [28.4],
        [25.5],
        [33.3],
        [36. ],
        [35. ],
        [35.4],
        [36.5],
        [36.3],
        [36.7],
        [36.1],
        [35.8],
        [32.8],
        [30.3],
        [26.4],
        [27.1],
        [33.6],
        [35.6],
        [29.6],
        [20.1],
        [17.7],
        [25.9],
        [21.3],
        [16.4],
        [24.8],
        [30. ],
        [33.8],
        [32.6],
        [32.2],
        [29.2],
        [31.1],
        [32. 

In [27]:
# 可调
poly_coe = 20

In [31]:
# 设置多项式的系数和常数项

w = tf.Variable(tf.random.normal(shape=(poly_coe+1, 1), mean = 0, stddev=0.01), trainable=True)


In [32]:
w

<tf.Variable 'Variable:0' shape=(21, 1) dtype=float32, numpy=
array([[-0.00144208],
       [-0.00225611],
       [-0.00171656],
       [-0.01061656],
       [ 0.01449835],
       [-0.00307326],
       [ 0.00963353],
       [ 0.00401075],
       [ 0.01192834],
       [-0.00353739],
       [ 0.00182234],
       [ 0.01456929],
       [ 0.01262105],
       [ 0.00290134],
       [-0.01439746],
       [-0.00179042],
       [-0.01026441],
       [ 0.00411427],
       [ 0.00017832],
       [ 0.01348951],
       [-0.00779494]], dtype=float32)>

In [33]:
# 设置data iter updater
def data_iter(batch_size, train_data, train_label):
    number_data = len(train_data)
    indices = list(range(number_data))
    random.shuffle(indices)
    for i in range(0, number_data, batch_size):
        j = tf.constant(indices[i:min(i+batch_size, number_data)])
        yield tf.gather(features, j), tf.gather(labels, j)